name: 'nba_analytics'
version: '1.0.0'
config-version: 2

profile: 'nba_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  nba_analytics:
    +materialized: table
    +schema: nba_analytics
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table