-- NFL Raw Data Tables Schema
-- This file contains the SQL schema for NFL raw data tables

-- Create schema for NFL raw data
CREATE SCHEMA IF NOT EXISTS nfl_raw;

-- Teams table
CREATE TABLE IF NOT EXISTS nfl_raw.teams (
    team_id VARCHAR(10) PRIMARY KEY,
    team_name VARCHAR(100) NOT NULL,
    team_abbreviation VARCHAR(10),
    team_conference VARCHAR(50),
    team_division VARCHAR(50),
    team_color VARCHAR(20),
    team_color_alt VARCHAR(20),
    team_logo VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Players table
CREATE TABLE IF NOT EXISTS nfl_raw.players (
    player_id VARCHAR(20) PRIMARY KEY,
    player_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    position VARCHAR(10),
    height VARCHAR(10),
    weight INTEGER,
    birth_date DATE,
    college VARCHAR(100),
    draft_year INTEGER,
    draft_round INTEGER,
    draft_pick INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Games table
CREATE TABLE IF NOT EXISTS nfl_raw.games (
    game_id VARCHAR(20) PRIMARY KEY,
    season INTEGER NOT NULL,
    week INTEGER,
    season_type VARCHAR(20),
    game_date DATE,
    game_time TIME,
    home_team VARCHAR(10),
    away_team VARCHAR(10),
    home_score INTEGER,
    away_score INTEGER,
    home_win BOOLEAN,
    stadium VARCHAR(100),
    weather VARCHAR(100),
    temperature INTEGER,
    humidity INTEGER,
    wind_speed INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Play-by-play data table
CREATE TABLE IF NOT EXISTS nfl_raw.play_by_play (
    play_id VARCHAR(50) PRIMARY KEY,
    game_id VARCHAR(20) NOT NULL,
    play_type VARCHAR(50),
    quarter INTEGER,
    quarter_time_remaining VARCHAR(10),
    down INTEGER,
    distance INTEGER,
    yard_line INTEGER,
    yard_line_side VARCHAR(10),
    formation VARCHAR(50),
    play_direction VARCHAR(10),
    personnel VARCHAR(50),
    personnel_offense VARCHAR(50),
    personnel_defense VARCHAR(50),
    play_nfl_id VARCHAR(50),
    play_description TEXT,
    possession_team VARCHAR(10),
    defensive_team VARCHAR(10),
    home_team VARCHAR(10),
    away_team VARCHAR(10),
    yardline_100 INTEGER,
    game_clock VARCHAR(10),
    quarter_seconds_remaining INTEGER,
    half_seconds_remaining INTEGER,
    game_seconds_remaining INTEGER,
    half_seconds_remaining_2 INTEGER,
    game_seconds_remaining_2 INTEGER,
    half_seconds_remaining_3 INTEGER,
    game_seconds_remaining_3 INTEGER,
    half_seconds_remaining_4 INTEGER,
    game_seconds_remaining_4 INTEGER,
    half_seconds_remaining_5 INTEGER,
    game_seconds_remaining_5 INTEGER,
    time_of_day VARCHAR(10),
    play_clock VARCHAR(10),
    down_and_distance VARCHAR(20),
    yard_line_fixed INTEGER,
    yard_line_direction VARCHAR(10),
    is_goal_line BOOLEAN,
    fixed_drive INTEGER,
    drive_number INTEGER,
    play_number INTEGER,
    drive_play_count INTEGER,
    drive_time_of_possession VARCHAR(10),
    drive_first_downs INTEGER,
    drive_inside_20 BOOLEAN,
    drive_ended_with_score BOOLEAN,
    drive_quarter_start INTEGER,
    drive_quarter_end INTEGER,
    drive_yards_penalized INTEGER,
    drive_start_transition VARCHAR(50),
    drive_end_transition VARCHAR(50),
    drive_game_clock_start VARCHAR(10),
    drive_game_clock_end VARCHAR(10),
    drive_start_yard_line INTEGER,
    drive_end_yard_line INTEGER,
    drive_play_count_ended_score INTEGER,
    drive_quarter_start_2 INTEGER,
    drive_quarter_end_2 INTEGER,
    drive_yards_penalized_2 INTEGER,
    drive_start_transition_2 VARCHAR(50),
    drive_end_transition_2 VARCHAR(50),
    drive_game_clock_start_2 VARCHAR(10),
    drive_game_clock_end_2 VARCHAR(10),
    drive_start_yard_line_2 INTEGER,
    drive_end_yard_line_2 INTEGER,
    drive_play_count_ended_score_2 INTEGER,
    drive_quarter_start_3 INTEGER,
    drive_quarter_end_3 INTEGER,
    drive_yards_penalized_3 INTEGER,
    drive_start_transition_3 VARCHAR(50),
    drive_end_transition_3 VARCHAR(50),
    drive_game_clock_start_3 VARCHAR(10),
    drive_game_clock_end_3 VARCHAR(10),
    drive_start_yard_line_3 INTEGER,
    drive_end_yard_line_3 INTEGER,
    drive_play_count_ended_score_3 INTEGER,
    drive_quarter_start_4 INTEGER,
    drive_quarter_end_4 INTEGER,
    drive_yards_penalized_4 INTEGER,
    drive_start_transition_4 VARCHAR(50),
    drive_end_transition_4 VARCHAR(50),
    drive_game_clock_start_4 VARCHAR(10),
    drive_game_clock_end_4 VARCHAR(10),
    drive_start_yard_line_4 INTEGER,
    drive_end_yard_line_4 INTEGER,
    drive_play_count_ended_score_4 INTEGER,
    drive_quarter_start_5 INTEGER,
    drive_quarter_end_5 INTEGER,
    drive_yards_penalized_5 INTEGER,
    drive_start_transition_5 VARCHAR(50),
    drive_end_transition_5 VARCHAR(50),
    drive_game_clock_start_5 VARCHAR(10),
    drive_game_clock_end_5 VARCHAR(10),
    drive_start_yard_line_5 INTEGER,
    drive_end_yard_line_5 INTEGER,
    drive_play_count_ended_score_5 INTEGER,
    score_play BOOLEAN,
    score_home INTEGER,
    score_away INTEGER,
    score_play_2 BOOLEAN,
    score_home_2 INTEGER,
    score_away_2 INTEGER,
    score_play_3 BOOLEAN,
    score_home_3 INTEGER,
    score_away_3 INTEGER,
    score_play_4 BOOLEAN,
    score_home_4 INTEGER,
    score_away_4 INTEGER,
    score_play_5 BOOLEAN,
    score_home_5 INTEGER,
    score_away_5 INTEGER,
    score_play_6 BOOLEAN,
    score_home_6 INTEGER,
    score_away_6 INTEGER,
    score_play_7 BOOLEAN,
    score_home_7 INTEGER,
    score_away_7 INTEGER,
    score_play_8 BOOLEAN,
    score_home_8 INTEGER,
    score_away_8 INTEGER,
    score_play_9 BOOLEAN,
    score_home_9 INTEGER,
    score_away_9 INTEGER,
    score_play_10 BOOLEAN,
    score_home_10 INTEGER,
    score_away_10 INTEGER,
    score_play_11 BOOLEAN,
    score_home_11 INTEGER,
    score_away_11 INTEGER,
    score_play_12 BOOLEAN,
    score_home_12 INTEGER,
    score_away_12 INTEGER,
    score_play_13 BOOLEAN,
    score_home_13 INTEGER,
    score_away_13 INTEGER,
    score_play_14 BOOLEAN,
    score_home_14 INTEGER,
    score_away_14 INTEGER,
    score_play_15 BOOLEAN,
    score_home_15 INTEGER,
    score_away_15 INTEGER,
    score_play_16 BOOLEAN,
    score_home_16 INTEGER,
    score_away_16 INTEGER,
    score_play_17 BOOLEAN,
    score_home_17 INTEGER,
    score_away_17 INTEGER,
    score_play_18 BOOLEAN,
    score_home_18 INTEGER,
    score_away_18 INTEGER,
    score_play_19 BOOLEAN,
    score_home_19 INTEGER,
    score_away_19 INTEGER,
    score_play_20 BOOLEAN,
    score_home_20 INTEGER,
    score_away_20 INTEGER,
    score_play_21 BOOLEAN,
    score_home_21 INTEGER,
    score_away_21 INTEGER,
    score_play_22 BOOLEAN,
    score_home_22 INTEGER,
    score_away_22 INTEGER,
    score_play_23 BOOLEAN,
    score_home_23 INTEGER,
    score_away_23 INTEGER,
    score_play_24 BOOLEAN,
    score_home_24 INTEGER,
    score_away_24 INTEGER,
    score_play_25 BOOLEAN,
    score_home_25 INTEGER,
    score_away_25 INTEGER,
    score_play_26 BOOLEAN,
    score_home_26 INTEGER,
    score_away_26 INTEGER,
    score_play_27 BOOLEAN,
    score_home_27 INTEGER,
    score_away_27 INTEGER,
    score_play_28 BOOLEAN,
    score_home_28 INTEGER,
    score_away_28 INTEGER,
    score_play_29 BOOLEAN,
    score_home_29 INTEGER,
    score_away_29 INTEGER,
    score_play_30 BOOLEAN,
    score_home_30 INTEGER,
    score_away_30 INTEGER,
    score_play_31 BOOLEAN,
    score_home_31 INTEGER,
    score_away_31 INTEGER,
    score_play_32 BOOLEAN,
    score_home_32 INTEGER,
    score_away_32 INTEGER,
    score_play_33 BOOLEAN,
    score_home_33 INTEGER,
    score_away_33 INTEGER,
    score_play_34 BOOLEAN,
    score_home_34 INTEGER,
    score_away_34 INTEGER,
    score_play_35 BOOLEAN,
    score_home_35 INTEGER,
    score_away_35 INTEGER,
    score_play_36 BOOLEAN,
    score_home_36 INTEGER,
    score_away_36 INTEGER,
    score_play_37 BOOLEAN,
    score_home_37 INTEGER,
    score_away_37 INTEGER,
    score_play_38 BOOLEAN,
    score_home_38 INTEGER,
    score_away_38 INTEGER,
    score_play_39 BOOLEAN,
    score_home_39 INTEGER,
    score_away_39 INTEGER,
    score_play_40 BOOLEAN,
    score_home_40 INTEGER,
    score_away_40 INTEGER,
    score_play_41 BOOLEAN,
    score_home_41 INTEGER,
    score_away_41 INTEGER,
    score_play_42 BOOLEAN,
    score_home_42 INTEGER,
    score_away_42 INTEGER,
    score_play_43 BOOLEAN,
    score_home_43 INTEGER,
    score_away_43 INTEGER,
    score_play_44 BOOLEAN,
    score_home_44 INTEGER,
    score_away_44 INTEGER,
    score_play_45 BOOLEAN,
    score_home_45 INTEGER,
    score_away_45 INTEGER,
    score_play_46 BOOLEAN,
    score_home_46 INTEGER,
    score_away_46 INTEGER,
    score_play_47 BOOLEAN,
    score_home_47 INTEGER,
    score_away_47 INTEGER,
    score_play_48 BOOLEAN,
    score_home_48 INTEGER,
    score_away_48 INTEGER,
    score_play_49 BOOLEAN,
    score_home_49 INTEGER,
    score_away_49 INTEGER,
    score_play_50 BOOLEAN,
    score_home_50 INTEGER,
    score_away_50 INTEGER,
    score_play_51 BOOLEAN,
    score_home_51 INTEGER,
    score_away_51 INTEGER,
    score_play_52 BOOLEAN,
    score_home_52 INTEGER,
    score_away_52 INTEGER,
    score_play_53 BOOLEAN,
    score_home_53 INTEGER,
    score_away_53 INTEGER,
    score_play_54 BOOLEAN,
    score_home_54 INTEGER,
    score_away_54 INTEGER,
    score_play_55 BOOLEAN,
    score_home_55 INTEGER,
    score_away_55 INTEGER,
    score_play_56 BOOLEAN,
    score_home_56 INTEGER,
    score_away_56 INTEGER,
    score_play_57 BOOLEAN,
    score_home_57 INTEGER,
    score_away_57 INTEGER,
    score_play_58 BOOLEAN,
    score_home_58 INTEGER,
    score_away_58 INTEGER,
    score_play_59 BOOLEAN,
    score_home_59 INTEGER,
    score_away_59 INTEGER,
    score_play_60 BOOLEAN,
    score_home_60 INTEGER,
    score_away_60 INTEGER,
    score_play_61 BOOLEAN,
    score_home_61 INTEGER,
    score_away_61 INTEGER,
    score_play_62 BOOLEAN,
    score_home_62 INTEGER,
    score_away_62 INTEGER,
    score_play_63 BOOLEAN,
    score_home_63 INTEGER,
    score_away_63 INTEGER,
    score_play_64 BOOLEAN,
    score_home_64 INTEGER,
    score_away_64 INTEGER,
    score_play_65 BOOLEAN,
    score_home_65 INTEGER,
    score_away_65 INTEGER,
    score_play_66 BOOLEAN,
    score_home_66 INTEGER,
    score_away_66 INTEGER,
    score_play_67 BOOLEAN,
    score_home_67 INTEGER,
    score_away_67 INTEGER,
    score_play_68 BOOLEAN,
    score_home_68 INTEGER,
    score_away_68 INTEGER,
    score_play_69 BOOLEAN,
    score_home_69 INTEGER,
    score_away_69 INTEGER,
    score_play_70 BOOLEAN,
    score_home_70 INTEGER,
    score_away_70 INTEGER,
    score_play_71 BOOLEAN,
    score_home_71 INTEGER,
    score_away_71 INTEGER,
    score_play_72 BOOLEAN,
    score_home_72 INTEGER,
    score_away_72 INTEGER,
    score_play_73 BOOLEAN,
    score_home_73 INTEGER,
    score_away_73 INTEGER,
    score_play_74 BOOLEAN,
    score_home_74 INTEGER,
    score_away_74 INTEGER,
    score_play_75 BOOLEAN,
    score_home_75 INTEGER,
    score_away_75 INTEGER,
    score_play_76 BOOLEAN,
    score_home_76 INTEGER,
    score_away_76 INTEGER,
    score_play_77 BOOLEAN,
    score_home_77 INTEGER,
    score_away_77 INTEGER,
    score_play_78 BOOLEAN,
    score_home_78 INTEGER,
    score_away_78 INTEGER,
    score_play_79 BOOLEAN,
    score_home_79 INTEGER,
    score_away_79 INTEGER,
    score_play_80 BOOLEAN,
    score_home_80 INTEGER,
    score_away_80 INTEGER,
    score_play_81 BOOLEAN,
    score_home_81 INTEGER,
    score_away_81 INTEGER,
    score_play_82 BOOLEAN,
    score_home_82 INTEGER,
    score_away_82 INTEGER,
    score_play_83 BOOLEAN,
    score_home_83 INTEGER,
    score_away_83 INTEGER,
    score_play_84 BOOLEAN,
    score_home_84 INTEGER,
    score_away_84 INTEGER,
    score_play_85 BOOLEAN,
    score_home_85 INTEGER,
    score_away_85 INTEGER,
    score_play_86 BOOLEAN,
    score_home_86 INTEGER,
    score_away_86 INTEGER,
    score_play_87 BOOLEAN,
    score_home_87 INTEGER,
    score_away_87 INTEGER,
    score_play_88 BOOLEAN,
    score_home_88 INTEGER,
    score_away_88 INTEGER,
    score_play_89 BOOLEAN,
    score_home_89 INTEGER,
    score_away_89 INTEGER,
    score_play_90 BOOLEAN,
    score_home_90 INTEGER,
    score_away_90 INTEGER,
    score_play_91 BOOLEAN,
    score_home_91 INTEGER,
    score_away_91 INTEGER,
    score_play_92 BOOLEAN,
    score_home_92 INTEGER,
    score_away_92 INTEGER,
    score_play_93 BOOLEAN,
    score_home_93 INTEGER,
    score_away_93 INTEGER,
    score_play_94 BOOLEAN,
    score_home_94 INTEGER,
    score_away_94 INTEGER,
    score_play_95 BOOLEAN,
    score_home_95 INTEGER,
    score_away_95 INTEGER,
    score_play_96 BOOLEAN,
    score_home_96 INTEGER,
    score_away_96 INTEGER,
    score_play_97 BOOLEAN,
    score_home_97 INTEGER,
    score_away_97 INTEGER,
    score_play_98 BOOLEAN,
    score_home_98 INTEGER,
    score_away_98 INTEGER,
    score_play_99 BOOLEAN,
    score_home_99 INTEGER,
    score_away_99 INTEGER,
    score_play_100 BOOLEAN,
    score_home_100 INTEGER,
    score_away_100 INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (game_id) REFERENCES nfl_raw.games(game_id)
);

-- Player stats table
CREATE TABLE IF NOT EXISTS nfl_raw.player_stats (
    stat_id VARCHAR(50) PRIMARY KEY,
    game_id VARCHAR(20) NOT NULL,
    player_id VARCHAR(20) NOT NULL,
    team VARCHAR(10),
    player_name VARCHAR(100),
    position VARCHAR(10),
    passing_attempts INTEGER,
    passing_completions INTEGER,
    passing_yards INTEGER,
    passing_touchdowns INTEGER,
    passing_interceptions INTEGER,
    passing_sacks INTEGER,
    passing_sack_yards INTEGER,
    passing_long INTEGER,
    passing_rating DECIMAL(5,2),
    rushing_attempts INTEGER,
    rushing_yards INTEGER,
    rushing_touchdowns INTEGER,
    rushing_long INTEGER,
    receiving_targets INTEGER,
    receiving_receptions INTEGER,
    receiving_yards INTEGER,
    receiving_touchdowns INTEGER,
    receiving_long INTEGER,
    fumbles INTEGER,
    fumbles_lost INTEGER,
    interceptions INTEGER,
    interception_yards INTEGER,
    interception_touchdowns INTEGER,
    passes_defended INTEGER,
    tackles INTEGER,
    tackles_assisted INTEGER,
    sacks INTEGER,
    sack_yards INTEGER,
    tackles_for_loss INTEGER,
    tackles_for_loss_yards INTEGER,
    quarterback_hits INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (game_id) REFERENCES nfl_raw.games(game_id),
    FOREIGN KEY (player_id) REFERENCES nfl_raw.players(player_id)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_play_by_play_game_id ON nfl_raw.play_by_play(game_id);
CREATE INDEX IF NOT EXISTS idx_play_by_play_play_type ON nfl_raw.play_by_play(play_type);
CREATE INDEX IF NOT EXISTS idx_player_stats_game_id ON nfl_raw.player_stats(game_id);
CREATE INDEX IF NOT EXISTS idx_player_stats_player_id ON nfl_raw.player_stats(player_id);
CREATE INDEX IF NOT EXISTS idx_games_season ON nfl_raw.games(season);
CREATE INDEX IF NOT EXISTS idx_games_teams ON nfl_raw.games(home_team, away_team);
